name: iOS starter workflow

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - xcode: "14.3"
            ios: "15.1"
    steps:
    - uses: actions/checkout@v3
    # - name: Xcode Setup
    #   uses: maxim-lobanov/setup-xcode@v1
    #   with:
    #     xcode-version: '14.1'

    # - name: Build
    #   run: |
    #     xcodebuild build -scheme Petto -project Petto.xcodeproj clean build -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=No
    - uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: Petto.xcodeproj
        scheme: Petto
        destination: platform=iOS
        action: build
